using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http;
using ProjectManagementTracketAPI.ExceptionHandler;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace ProjectManagementTracketAPI.ExceptionHnadler
{
    public static class ExceptionHandler
    {

        public static void ConfigureExceptionHandler(this IApplicationBuilder app, ILog logger)
        {
            app.UseExceptionHandler(appError =>
            {
                appError.Run(async context =>
                {
                    context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                    context.Response.ContentType = "application/json";

                    var contextFeature = context.Features.Get<IExceptionHandlerFeature>();
                    if (contextFeature != null)
                    {
                        logger.Error($"Something went wrong: {contextFeature.Error}");

                        await context.Response.WriteAsync(new ErrorDetails()
                        {
                            StatusCode = context.Response.StatusCode,
                            Message = "Internal Server Error. Error generated by NLog!"
                        }.ToString());
                    }
                });
            });
        }
        //public static void ConfigureExceptionHandler(this IApplicationBuilder app)
        //{
        //     app.UseExceptionHandler(error =>
        //      {
        //          error.Run(async context => {
        //              var contextFeature = context.Features.Get<IExceptionHandlerFeature>();
        //              if (contextFeature != null)
        //              {
        //                  DateTime logDateTime = DateTime.Now;
        //                  string error = contextFeature.Error.Message;
        //                  string stackTrac = contextFeature.Error.StackTrace.ToString();


        //              }


        //          });
        //      });
        //}
    }
}
